# Generated by Django 5.2.5 on 2025-08-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhaiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritentReferenceUnit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nutrient', models.CharField(max_length=20, unique=True)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='aminoacid',
            name='ala',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='aminoacid',
            name='arg',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='aminoacid',
            name='asp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='aminoacid',
            name='glu',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='aminoacid',
            name='gly',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='aminoacid',
            name='pro',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='aminoacid',
            name='ser',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='aminoacid',
            name='tyr',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
