# Generated by Django 5.2.5 on 2025-08-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhaiapp', '0002_nutritentreferenceunit_aminoacid_ala_aminoacid_arg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategorymap',
            name='ifct_code',
            field=models.CharField(blank=True, max_length=3, null=True, unique=True),
        ),
    ]
