# Generated by Django 5.2.5 on 2025-08-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhaiapp', '0003_foodcategorymap_ifct_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategorymap',
            name='ifct_code',
            field=models.CharField(blank=True, max_length=2, null=True, unique=True),
        ),
    ]
