# Generated by Django 5.2.5 on 2025-08-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhaiapp', '0004_alter_foodcategorymap_ifct_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
