# Generated by Django 5.2.5 on 2025-08-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhaiapp', '0005_alter_food_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodcategorymap',
            name='ifct_code',
        ),
        migrations.AddField(
            model_name='foodcategorymap',
            name='category_code',
            field=models.CharField(blank=True, max_length=3, null=True, unique=True),
        ),
    ]
