# Generated by Django 5.1.4 on 2025-08-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhaiapp', '0006_remove_foodcategorymap_ifct_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polyphenols',
            name='hbenzaldehyde',
        ),
        migrations.AddField(
            model_name='aminoacid',
            name='ala_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Alanine Standard Deviation'),
        ),
        migrations.AddField(
            model_name='aminoacid',
            name='arg_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Arginine Standard Deviation'),
        ),
        migrations.AddField(
            model_name='aminoacid',
            name='asp_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Aspartic Acid Standard Deviation'),
        ),
        migrations.AddField(
            model_name='aminoacid',
            name='cys_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Cysteine Standard Deviation'),
        ),
        migrations.AddField(
            model_name='aminoacid',
            name='glu_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Glutamic Acid Standard Deviation'),
        ),
        migrations.AddField(
            model_name='aminoacid',
            name='gly_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Glycine Standard Deviation'),
        ),
        migrations.AddField(
            model_name='aminoacid',
            name='his_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Histidine Standard Deviation'),
        ),
        migrations.AddField(
            model_name='aminoacid',
            name='ile_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Isoleucine Standard Deviation'),
        ),
        migrations.AddField(
            model_name='aminoacid',
            name='leu_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Leucine Standard Deviation'),
        ),
        migrations.AddField(
            model_name='aminoacid',
            name='lys_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Lysine Standard Deviation'),
        ),
        migrations.AddField(
            model_name='aminoacid',
            name='met_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Methionine Standard Deviation'),
        ),
        migrations.AddField(
            model_name='aminoacid',
            name='phe_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Phenylalanine Standard Deviation'),
        ),
        migrations.AddField(
            model_name='aminoacid',
            name='pro_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Proline Standard Deviation'),
        ),
        migrations.AddField(
            model_name='aminoacid',
            name='ser_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Serine Standard Deviation'),
        ),
        migrations.AddField(
            model_name='aminoacid',
            name='thr_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Threonine Standard Deviation'),
        ),
        migrations.AddField(
            model_name='aminoacid',
            name='trp_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Tryptophan Standard Deviation'),
        ),
        migrations.AddField(
            model_name='aminoacid',
            name='tyr_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Tyrosine Standard Deviation'),
        ),
        migrations.AddField(
            model_name='aminoacid',
            name='val_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Valine Standard Deviation'),
        ),
        migrations.AddField(
            model_name='carotenoids',
            name='carta_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Carotene A Standard Deviation'),
        ),
        migrations.AddField(
            model_name='carotenoids',
            name='cartb_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Carotene B Standard Deviation'),
        ),
        migrations.AddField(
            model_name='carotenoids',
            name='cartg_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Carotene G Standard Deviation'),
        ),
        migrations.AddField(
            model_name='carotenoids',
            name='cartoid_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Total Carotenoids Standard Deviation'),
        ),
        migrations.AddField(
            model_name='carotenoids',
            name='crypxb_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Cryptoxanthin Standard Deviation'),
        ),
        migrations.AddField(
            model_name='carotenoids',
            name='lutn_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Lutein Standard Deviation'),
        ),
        migrations.AddField(
            model_name='carotenoids',
            name='lycpn_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Lycopene Standard Deviation'),
        ),
        migrations.AddField(
            model_name='carotenoids',
            name='zea_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Zeaxanthin Standard Deviation'),
        ),
        migrations.AddField(
            model_name='dietaryfibre',
            name='ash_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Ash Content Standard Deviation'),
        ),
        migrations.AddField(
            model_name='dietaryfibre',
            name='choavldf_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Available Carbohydrates Standard Deviation'),
        ),
        migrations.AddField(
            model_name='dietaryfibre',
            name='enerc_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Energy Content Standard Deviation'),
        ),
        migrations.AddField(
            model_name='dietaryfibre',
            name='fatce_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Fat Content Standard Deviation'),
        ),
        migrations.AddField(
            model_name='dietaryfibre',
            name='fibins_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Insoluble Dietary Fibre Standard Deviation'),
        ),
        migrations.AddField(
            model_name='dietaryfibre',
            name='fibsol_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Soluble Dietary Fibre Standard Deviation'),
        ),
        migrations.AddField(
            model_name='dietaryfibre',
            name='fibtg_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Total Dietary Fibre Standard Deviation'),
        ),
        migrations.AddField(
            model_name='dietaryfibre',
            name='protcnt_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Protein Content Standard Deviation'),
        ),
        migrations.AddField(
            model_name='fatsolublevitamins',
            name='chocal_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Cholecalciferol Standard Deviation'),
        ),
        migrations.AddField(
            model_name='fatsolublevitamins',
            name='ergcal_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Ergocalciferol Standard Deviation'),
        ),
        migrations.AddField(
            model_name='fatsolublevitamins',
            name='retol_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Retinol Standard Deviation'),
        ),
        migrations.AddField(
            model_name='fatsolublevitamins',
            name='tocpha_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Tocopherol A Standard Deviation'),
        ),
        migrations.AddField(
            model_name='fatsolublevitamins',
            name='tocphb_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Tocopherol B Standard Deviation'),
        ),
        migrations.AddField(
            model_name='fatsolublevitamins',
            name='tocphd_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Tocopherol D Standard Deviation'),
        ),
        migrations.AddField(
            model_name='fatsolublevitamins',
            name='tocphg_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Tocopherol G Standard Deviation'),
        ),
        migrations.AddField(
            model_name='fatsolublevitamins',
            name='toctra_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Tocotrienol A Standard Deviation'),
        ),
        migrations.AddField(
            model_name='fatsolublevitamins',
            name='toctrb_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Tocotrienol B Standard Deviation'),
        ),
        migrations.AddField(
            model_name='fatsolublevitamins',
            name='toctrd_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Tocotrienol D Standard Deviation'),
        ),
        migrations.AddField(
            model_name='fatsolublevitamins',
            name='toctrg_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Tocotrienol G Standard Deviation'),
        ),
        migrations.AddField(
            model_name='fatsolublevitamins',
            name='vite_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Vitamin E Standard Deviation'),
        ),
        migrations.AddField(
            model_name='fatsolublevitamins',
            name='vitk1_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Vitamin K1 Standard Deviation'),
        ),
        migrations.AddField(
            model_name='fatsolublevitamins',
            name='vitk2_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Vitamin K2 Standard Deviation'),
        ),
        migrations.AddField(
            model_name='fattyacid',
            name='f10d0_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='C10:0 Standard Deviation'),
        ),
        migrations.AddField(
            model_name='fattyacid',
            name='f12d0_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='C12:0 Standard Deviation'),
        ),
        migrations.AddField(
            model_name='fattyacid',
            name='f14d0_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='C14:0 Standard Deviation'),
        ),
        migrations.AddField(
            model_name='fattyacid',
            name='f14d1_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='C14:1 Standard Deviation'),
        ),
        migrations.AddField(
            model_name='fattyacid',
            name='f16d0_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='C16:0 Standard Deviation'),
        ),
        migrations.AddField(
            model_name='fattyacid',
            name='f16d1_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='C16:1 Standard Deviation'),
        ),
        migrations.AddField(
            model_name='fattyacid',
            name='f18d0_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='C18:0 Standard Deviation'),
        ),
        migrations.AddField(
            model_name='fattyacid',
            name='f18d1n9_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='C18:1n9 Standard Deviation'),
        ),
        migrations.AddField(
            model_name='fattyacid',
            name='f18d1tn9_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='C18:1t9 Standard Deviation'),
        ),
        migrations.AddField(
            model_name='fattyacid',
            name='f18d2n6_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='C18:2n6 Standard Deviation'),
        ),
        migrations.AddField(
            model_name='fattyacid',
            name='f18d3n3_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='C18:3n3 Standard Deviation'),
        ),
        migrations.AddField(
            model_name='fattyacid',
            name='f20d0_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='C20:0 Standard Deviation'),
        ),
        migrations.AddField(
            model_name='fattyacid',
            name='f20d1n9_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='C20:1n9 Standard Deviation'),
        ),
        migrations.AddField(
            model_name='fattyacid',
            name='f20d2_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='C20:2 Standard Deviation'),
        ),
        migrations.AddField(
            model_name='fattyacid',
            name='f20d4n6_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='C20:4n6 Standard Deviation'),
        ),
        migrations.AddField(
            model_name='fattyacid',
            name='f22d0_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='C22:0 Standard Deviation'),
        ),
        migrations.AddField(
            model_name='fattyacid',
            name='f22d1n9_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='C22:1n9 Standard Deviation'),
        ),
        migrations.AddField(
            model_name='fattyacid',
            name='f24d0_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='C24:0 Standard Deviation'),
        ),
        migrations.AddField(
            model_name='fattyacid',
            name='f24d1n9_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='C24:1n9 Standard Deviation'),
        ),
        migrations.AddField(
            model_name='fattyacid',
            name='f4d0_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='C4:0 Standard Deviation'),
        ),
        migrations.AddField(
            model_name='fattyacid',
            name='f6d0_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='C6:0 Standard Deviation'),
        ),
        migrations.AddField(
            model_name='fattyacid',
            name='f8d0_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='C8:0 Standard Deviation'),
        ),
        migrations.AddField(
            model_name='fattyacid',
            name='fams_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Total Monounsaturated Fatty Acids Standard Deviation'),
        ),
        migrations.AddField(
            model_name='fattyacid',
            name='fapu_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Total Polyunsaturated Fatty Acids Standard Deviation'),
        ),
        migrations.AddField(
            model_name='fattyacid',
            name='fasat_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Total Saturated Fatty Acids Standard Deviation'),
        ),
        migrations.AddField(
            model_name='mineralsandtraceelements',
            name='As_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Arsenic Standard Deviation'),
        ),
        migrations.AddField(
            model_name='mineralsandtraceelements',
            name='al_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Aluminum Standard Deviation'),
        ),
        migrations.AddField(
            model_name='mineralsandtraceelements',
            name='ca_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Calcium Standard Deviation'),
        ),
        migrations.AddField(
            model_name='mineralsandtraceelements',
            name='cd_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Cadmium Standard Deviation'),
        ),
        migrations.AddField(
            model_name='mineralsandtraceelements',
            name='co_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Cobalt Standard Deviation'),
        ),
        migrations.AddField(
            model_name='mineralsandtraceelements',
            name='cr_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Chromium Standard Deviation'),
        ),
        migrations.AddField(
            model_name='mineralsandtraceelements',
            name='cu_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Copper Standard Deviation'),
        ),
        migrations.AddField(
            model_name='mineralsandtraceelements',
            name='fe_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Iron Standard Deviation'),
        ),
        migrations.AddField(
            model_name='mineralsandtraceelements',
            name='hg_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Mercury Standard Deviation'),
        ),
        migrations.AddField(
            model_name='mineralsandtraceelements',
            name='k_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Potassium Standard Deviation'),
        ),
        migrations.AddField(
            model_name='mineralsandtraceelements',
            name='li_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Lithium Standard Deviation'),
        ),
        migrations.AddField(
            model_name='mineralsandtraceelements',
            name='mg_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Magnesium Standard Deviation'),
        ),
        migrations.AddField(
            model_name='mineralsandtraceelements',
            name='mn_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Manganese Standard Deviation'),
        ),
        migrations.AddField(
            model_name='mineralsandtraceelements',
            name='mo_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Molybdenum Standard Deviation'),
        ),
        migrations.AddField(
            model_name='mineralsandtraceelements',
            name='na_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Sodium Standard Deviation'),
        ),
        migrations.AddField(
            model_name='mineralsandtraceelements',
            name='ni_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Nickel Standard Deviation'),
        ),
        migrations.AddField(
            model_name='mineralsandtraceelements',
            name='p_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Phosphorus Standard Deviation'),
        ),
        migrations.AddField(
            model_name='mineralsandtraceelements',
            name='pb_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Lead Standard Deviation'),
        ),
        migrations.AddField(
            model_name='mineralsandtraceelements',
            name='se_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Selenium Standard Deviation'),
        ),
        migrations.AddField(
            model_name='mineralsandtraceelements',
            name='zn_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Zinc Standard Deviation'),
        ),
        migrations.AddField(
            model_name='oligosaccharides',
            name='ajus_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Ajugose Deviation'),
        ),
        migrations.AddField(
            model_name='oligosaccharides',
            name='rafs_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Raffinose Deviation'),
        ),
        migrations.AddField(
            model_name='oligosaccharides',
            name='stas_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Stachyose Deviation'),
        ),
        migrations.AddField(
            model_name='oligosaccharides',
            name='vers_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Verbacose Deviation'),
        ),
        migrations.AddField(
            model_name='organicacid',
            name='cisacoacid_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='cis-Aconitic Acid Standard Deviation'),
        ),
        migrations.AddField(
            model_name='organicacid',
            name='citac_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Citric Acid Standard Deviation'),
        ),
        migrations.AddField(
            model_name='organicacid',
            name='fumac_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Fumaric Acid Standard Deviation'),
        ),
        migrations.AddField(
            model_name='organicacid',
            name='malac_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Malic Acid Standard Deviation'),
        ),
        migrations.AddField(
            model_name='organicacid',
            name='oxalateins_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Water Insoluble Oxalate Standard Deviation'),
        ),
        migrations.AddField(
            model_name='organicacid',
            name='oxalatesol_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Water Soluble Oxalate Standard Deviation'),
        ),
        migrations.AddField(
            model_name='organicacid',
            name='oxalatetot_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Total Oxalate Standard Deviation'),
        ),
        migrations.AddField(
            model_name='organicacid',
            name='quinic_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Quinic Acid Standard Deviation'),
        ),
        migrations.AddField(
            model_name='organicacid',
            name='sucac_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Succinic Acid Standard Deviation'),
        ),
        migrations.AddField(
            model_name='organicacid',
            name='tarac_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Tartaric Acid Standard Deviation'),
        ),
        migrations.AddField(
            model_name='phytosterolsphytatesaponin',
            name='bsitosterol_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='beta-Sitosterol Deviation'),
        ),
        migrations.AddField(
            model_name='phytosterolsphytatesaponin',
            name='camt_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Campesterol Deviation'),
        ),
        migrations.AddField(
            model_name='phytosterolsphytatesaponin',
            name='phytac_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Phytate Deviation'),
        ),
        migrations.AddField(
            model_name='phytosterolsphytatesaponin',
            name='stgstr_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Stigmasterol Deviation'),
        ),
        migrations.AddField(
            model_name='phytosterolsphytatesaponin',
            name='totsaponin_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Total Saponin Deviation'),
        ),
        migrations.AddField(
            model_name='polyphenols',
            name='apigen_cg_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Apigenin-6-C-gluoside Deviation'),
        ),
        migrations.AddField(
            model_name='polyphenols',
            name='apigen_on_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Apegenin-7-O-neohesperidoside Deviation'),
        ),
        migrations.AddField(
            model_name='polyphenols',
            name='apigen_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Apigenin Deviation'),
        ),
        migrations.AddField(
            model_name='polyphenols',
            name='caffeic_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Caffeic Acid Deviation'),
        ),
        migrations.AddField(
            model_name='polyphenols',
            name='catechin_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='+ Catechin Deviation'),
        ),
        migrations.AddField(
            model_name='polyphenols',
            name='chlrac_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Chlorogenic Acid Deviation'),
        ),
        migrations.AddField(
            model_name='polyphenols',
            name='cinnamic_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Cinnamic Acid Deviation'),
        ),
        migrations.AddField(
            model_name='polyphenols',
            name='daidzn_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Daidzein Deviation'),
        ),
        migrations.AddField(
            model_name='polyphenols',
            name='dhbenzacid_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='3,4-Dihydroxybenzoic Acid Deviation'),
        ),
        migrations.AddField(
            model_name='polyphenols',
            name='dhbenzaldehyde',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='3-Dihydroxybenzaldehyde'),
        ),
        migrations.AddField(
            model_name='polyphenols',
            name='dhbenzaldehyde_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='3-Dihydroxybenzaldehyde Deviation'),
        ),
        migrations.AddField(
            model_name='polyphenols',
            name='ellagic_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Ellagic Acid Deviation'),
        ),
        migrations.AddField(
            model_name='polyphenols',
            name='epicatec_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='- Epicatechin Deviation'),
        ),
        migrations.AddField(
            model_name='polyphenols',
            name='epicategc_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='- Epigalocatechin Deviation'),
        ),
        migrations.AddField(
            model_name='polyphenols',
            name='epigalocg_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='- Epigalocatechin-3-gallate Deviation'),
        ),
        migrations.AddField(
            model_name='polyphenols',
            name='ferac_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Ferulic Acid Deviation'),
        ),
        migrations.AddField(
            model_name='polyphenols',
            name='gallic_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Gallic Acid Deviation'),
        ),
        migrations.AddField(
            model_name='polyphenols',
            name='gallocatechin_ga_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Gallocatechin gallate Deviation'),
        ),
        migrations.AddField(
            model_name='polyphenols',
            name='gallocatecin_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Gallocatechin Deviation'),
        ),
        migrations.AddField(
            model_name='polyphenols',
            name='gnstein_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Genistein Deviation'),
        ),
        migrations.AddField(
            model_name='polyphenols',
            name='hespd_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Hesperdin Deviation'),
        ),
        migrations.AddField(
            model_name='polyphenols',
            name='hespt_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Hesperetin Deviation'),
        ),
        migrations.AddField(
            model_name='polyphenols',
            name='isorhamnetin_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Isorhamnetin Deviation'),
        ),
        migrations.AddField(
            model_name='polyphenols',
            name='kaemf_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Kaempferol Deviation'),
        ),
        migrations.AddField(
            model_name='polyphenols',
            name='luteol_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Luteolin Deviation'),
        ),
        migrations.AddField(
            model_name='polyphenols',
            name='myricetin_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Myricetin Deviation'),
        ),
        migrations.AddField(
            model_name='polyphenols',
            name='naringenin_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Naringenin Deviation'),
        ),
        migrations.AddField(
            model_name='polyphenols',
            name='o_coumaric_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='O-Coumaric Acid Deviation'),
        ),
        migrations.AddField(
            model_name='polyphenols',
            name='p_coumaric_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='P-Coumaric Acid Deviation'),
        ),
        migrations.AddField(
            model_name='polyphenols',
            name='protocatechuic_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Protocatechuic Acid Deviation'),
        ),
        migrations.AddField(
            model_name='polyphenols',
            name='querce_bd_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Quercetin 3-beta-D-glucoside Deviation'),
        ),
        migrations.AddField(
            model_name='polyphenols',
            name='querce_bg_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Quercetin-3-beta-galactoside Deviation'),
        ),
        migrations.AddField(
            model_name='polyphenols',
            name='querce_or_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Quercetin 3-O-rutinoside Deviation'),
        ),
        migrations.AddField(
            model_name='polyphenols',
            name='querce_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Quercetin Deviation'),
        ),
        migrations.AddField(
            model_name='polyphenols',
            name='resveratol_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Resveratrol Deviation'),
        ),
        migrations.AddField(
            model_name='polyphenols',
            name='sinapinic_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Sinapinic Acid Deviation'),
        ),
        migrations.AddField(
            model_name='polyphenols',
            name='syringic_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Syringic Acid Deviation'),
        ),
        migrations.AddField(
            model_name='polyphenols',
            name='total_poly_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Total Polyphenols Deviation'),
        ),
        migrations.AddField(
            model_name='polyphenols',
            name='vanillic_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Vanillic Acid Deviation'),
        ),
        migrations.AddField(
            model_name='starchandsugars',
            name='frus_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Fructose Standard Deviation'),
        ),
        migrations.AddField(
            model_name='starchandsugars',
            name='glus_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Glucose Standard Deviation'),
        ),
        migrations.AddField(
            model_name='starchandsugars',
            name='mals_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Maltose Standard Deviation'),
        ),
        migrations.AddField(
            model_name='starchandsugars',
            name='starch_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Starch Standard Deviation'),
        ),
        migrations.AddField(
            model_name='starchandsugars',
            name='sucs_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Sucrose Standard Deviation'),
        ),
        migrations.AddField(
            model_name='starchandsugars',
            name='tacho_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Total Available Carbohydrates Standard Deviation'),
        ),
        migrations.AddField(
            model_name='starchandsugars',
            name='tfs_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Total Free Sugars Standard Deviation'),
        ),
        migrations.AddField(
            model_name='watersolublevitamins',
            name='biot_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Biotin Standard Deviation'),
        ),
        migrations.AddField(
            model_name='watersolublevitamins',
            name='folsum_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Folic Acid Standard Deviation'),
        ),
        migrations.AddField(
            model_name='watersolublevitamins',
            name='nia_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Niacin Standard Deviation'),
        ),
        migrations.AddField(
            model_name='watersolublevitamins',
            name='pantac_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Pantothenic Acid Standard Deviation'),
        ),
        migrations.AddField(
            model_name='watersolublevitamins',
            name='ribf_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Riboflavin Standard Deviation'),
        ),
        migrations.AddField(
            model_name='watersolublevitamins',
            name='thia_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Thiamine Standard Deviation'),
        ),
        migrations.AddField(
            model_name='watersolublevitamins',
            name='vitb6a_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Vitamin B6 Standard Deviation'),
        ),
        migrations.AddField(
            model_name='watersolublevitamins',
            name='vitc_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Vitamin C Standard Deviation'),
        ),
        migrations.AlterField(
            model_name='aminoacid',
            name='ala',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Alanine'),
        ),
        migrations.AlterField(
            model_name='aminoacid',
            name='arg',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Arginine'),
        ),
        migrations.AlterField(
            model_name='aminoacid',
            name='asp',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Aspartic Acid'),
        ),
        migrations.AlterField(
            model_name='aminoacid',
            name='cys',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Cysteine'),
        ),
        migrations.AlterField(
            model_name='aminoacid',
            name='glu',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Glutamic Acid'),
        ),
        migrations.AlterField(
            model_name='aminoacid',
            name='gly',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Glycine'),
        ),
        migrations.AlterField(
            model_name='aminoacid',
            name='his',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Histidine'),
        ),
        migrations.AlterField(
            model_name='aminoacid',
            name='ile',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Isoleucine'),
        ),
        migrations.AlterField(
            model_name='aminoacid',
            name='leu',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Leucine'),
        ),
        migrations.AlterField(
            model_name='aminoacid',
            name='lys',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Lysine'),
        ),
        migrations.AlterField(
            model_name='aminoacid',
            name='met',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Methionine'),
        ),
        migrations.AlterField(
            model_name='aminoacid',
            name='phe',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Phenylalanine'),
        ),
        migrations.AlterField(
            model_name='aminoacid',
            name='pro',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Proline'),
        ),
        migrations.AlterField(
            model_name='aminoacid',
            name='ser',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Serine'),
        ),
        migrations.AlterField(
            model_name='aminoacid',
            name='thr',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Threonine'),
        ),
        migrations.AlterField(
            model_name='aminoacid',
            name='trp',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Tryptophan'),
        ),
        migrations.AlterField(
            model_name='aminoacid',
            name='tyr',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Tyrosine'),
        ),
        migrations.AlterField(
            model_name='aminoacid',
            name='val',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Valine'),
        ),
        migrations.AlterField(
            model_name='carotenoids',
            name='carta',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Carotene A'),
        ),
        migrations.AlterField(
            model_name='carotenoids',
            name='cartb',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Carotene B'),
        ),
        migrations.AlterField(
            model_name='carotenoids',
            name='cartg',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Carotene G'),
        ),
        migrations.AlterField(
            model_name='carotenoids',
            name='cartoid',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Total Carotenoids'),
        ),
        migrations.AlterField(
            model_name='carotenoids',
            name='crypxb',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Cryptoxanthin'),
        ),
        migrations.AlterField(
            model_name='carotenoids',
            name='lutn',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Lutein'),
        ),
        migrations.AlterField(
            model_name='carotenoids',
            name='lycpn',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Lycopene'),
        ),
        migrations.AlterField(
            model_name='carotenoids',
            name='zea',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Zeaxanthin'),
        ),
        migrations.AlterField(
            model_name='dietaryfibre',
            name='ash',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Ash Content'),
        ),
        migrations.AlterField(
            model_name='dietaryfibre',
            name='choavldf',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Available Carbohydrates'),
        ),
        migrations.AlterField(
            model_name='dietaryfibre',
            name='enerc',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Energy Content'),
        ),
        migrations.AlterField(
            model_name='dietaryfibre',
            name='fatce',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Fat Content'),
        ),
        migrations.AlterField(
            model_name='dietaryfibre',
            name='fibins',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Insoluble Dietary Fibre'),
        ),
        migrations.AlterField(
            model_name='dietaryfibre',
            name='fibsol',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Soluble Dietary Fibre'),
        ),
        migrations.AlterField(
            model_name='dietaryfibre',
            name='fibtg',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Total Dietary Fibre'),
        ),
        migrations.AlterField(
            model_name='dietaryfibre',
            name='protcnt',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Protein Content'),
        ),
        migrations.AlterField(
            model_name='dietaryfibre',
            name='water',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Water Content'),
        ),
        migrations.AlterField(
            model_name='fatsolublevitamins',
            name='chocal',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Cholecalciferol (Vitamin D3)'),
        ),
        migrations.AlterField(
            model_name='fatsolublevitamins',
            name='ergcal',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Ergocalciferol (Vitamin D2)'),
        ),
        migrations.AlterField(
            model_name='fatsolublevitamins',
            name='retol',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Retinol (Vitamin A)'),
        ),
        migrations.AlterField(
            model_name='fatsolublevitamins',
            name='tocpha',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Tocopherol A (Vitamin E)'),
        ),
        migrations.AlterField(
            model_name='fatsolublevitamins',
            name='tocphb',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Tocopherol B (Vitamin E)'),
        ),
        migrations.AlterField(
            model_name='fatsolublevitamins',
            name='tocphd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Tocopherol D (Vitamin E)'),
        ),
        migrations.AlterField(
            model_name='fatsolublevitamins',
            name='tocphg',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Tocopherol G (Vitamin E)'),
        ),
        migrations.AlterField(
            model_name='fatsolublevitamins',
            name='toctra',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Tocotrienol A (Vitamin E)'),
        ),
        migrations.AlterField(
            model_name='fatsolublevitamins',
            name='toctrb',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Tocotrienol B (Vitamin E)'),
        ),
        migrations.AlterField(
            model_name='fatsolublevitamins',
            name='toctrd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Tocotrienol D (Vitamin E)'),
        ),
        migrations.AlterField(
            model_name='fatsolublevitamins',
            name='toctrg',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Tocotrienol G (Vitamin E)'),
        ),
        migrations.AlterField(
            model_name='fatsolublevitamins',
            name='vite',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Vitamin E'),
        ),
        migrations.AlterField(
            model_name='fatsolublevitamins',
            name='vitk1',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Vitamin K1'),
        ),
        migrations.AlterField(
            model_name='fatsolublevitamins',
            name='vitk2',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Vitamin K2'),
        ),
        migrations.AlterField(
            model_name='fattyacid',
            name='f10d0',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='C10:0 (Capric Acid)'),
        ),
        migrations.AlterField(
            model_name='fattyacid',
            name='f12d0',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='C12:0 (Lauric Acid)'),
        ),
        migrations.AlterField(
            model_name='fattyacid',
            name='f14d0',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='C14:0 (Myristic Acid)'),
        ),
        migrations.AlterField(
            model_name='fattyacid',
            name='f14d1',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='C14:1 (Myristoleic Acid)'),
        ),
        migrations.AlterField(
            model_name='fattyacid',
            name='f16d0',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='C16:0 (Palmitic Acid)'),
        ),
        migrations.AlterField(
            model_name='fattyacid',
            name='f16d1',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='C16:1 (Palmitoleic Acid)'),
        ),
        migrations.AlterField(
            model_name='fattyacid',
            name='f18d0',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='C18:0 (Stearic Acid)'),
        ),
        migrations.AlterField(
            model_name='fattyacid',
            name='f18d1n9',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='C18:1n9 (Oleic Acid)'),
        ),
        migrations.AlterField(
            model_name='fattyacid',
            name='f18d1tn9',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='C18:1t9 (Elaidic Acid )'),
        ),
        migrations.AlterField(
            model_name='fattyacid',
            name='f18d2n6',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='C18:2n6 (Linoleic Acid)'),
        ),
        migrations.AlterField(
            model_name='fattyacid',
            name='f18d3n3',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='C18:3n3 (Alpha-Linolenic Acid)'),
        ),
        migrations.AlterField(
            model_name='fattyacid',
            name='f20d0',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='C20:0 (Arachidic Acid)'),
        ),
        migrations.AlterField(
            model_name='fattyacid',
            name='f20d1n9',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='C20:1n9 (Gadoleic Acid)'),
        ),
        migrations.AlterField(
            model_name='fattyacid',
            name='f20d2',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='C20:2 (Eicosadienoic Acid)'),
        ),
        migrations.AlterField(
            model_name='fattyacid',
            name='f20d4n6',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='C20:4n6 (Arachidonic Acid)'),
        ),
        migrations.AlterField(
            model_name='fattyacid',
            name='f22d0',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='C22:0 (Behenic Acid)'),
        ),
        migrations.AlterField(
            model_name='fattyacid',
            name='f22d1n9',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='C22:1n9 (Erucic Acid)'),
        ),
        migrations.AlterField(
            model_name='fattyacid',
            name='f24d0',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='C24:0 (Lignoceric Acid)'),
        ),
        migrations.AlterField(
            model_name='fattyacid',
            name='f24d1n9',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='C24:1n9 (Nervonic Acid)'),
        ),
        migrations.AlterField(
            model_name='fattyacid',
            name='f4d0',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='C4:0 (Butyric Acid)'),
        ),
        migrations.AlterField(
            model_name='fattyacid',
            name='f6d0',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='C6:0 (Caproic Acid)'),
        ),
        migrations.AlterField(
            model_name='fattyacid',
            name='f8d0',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='C8:0 (Caprylic Acid)'),
        ),
        migrations.AlterField(
            model_name='fattyacid',
            name='fams',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Total Monounsaturated Fatty Acids'),
        ),
        migrations.AlterField(
            model_name='fattyacid',
            name='fapu',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Total Polyunsaturated Fatty Acids'),
        ),
        migrations.AlterField(
            model_name='fattyacid',
            name='fasat',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Total Saturated Fatty Acids'),
        ),
        migrations.AlterField(
            model_name='mineralsandtraceelements',
            name='As',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Arsenic'),
        ),
        migrations.AlterField(
            model_name='mineralsandtraceelements',
            name='al',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Aluminum'),
        ),
        migrations.AlterField(
            model_name='mineralsandtraceelements',
            name='ca',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Calcium'),
        ),
        migrations.AlterField(
            model_name='mineralsandtraceelements',
            name='cd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Cadmium'),
        ),
        migrations.AlterField(
            model_name='mineralsandtraceelements',
            name='co',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Cobalt'),
        ),
        migrations.AlterField(
            model_name='mineralsandtraceelements',
            name='cr',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Chromium'),
        ),
        migrations.AlterField(
            model_name='mineralsandtraceelements',
            name='cu',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Copper'),
        ),
        migrations.AlterField(
            model_name='mineralsandtraceelements',
            name='fe',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Iron'),
        ),
        migrations.AlterField(
            model_name='mineralsandtraceelements',
            name='hg',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Mercury'),
        ),
        migrations.AlterField(
            model_name='mineralsandtraceelements',
            name='k',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Potassium'),
        ),
        migrations.AlterField(
            model_name='mineralsandtraceelements',
            name='li',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Lithium'),
        ),
        migrations.AlterField(
            model_name='mineralsandtraceelements',
            name='mg',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Magnesium'),
        ),
        migrations.AlterField(
            model_name='mineralsandtraceelements',
            name='mn',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Manganese'),
        ),
        migrations.AlterField(
            model_name='mineralsandtraceelements',
            name='mo',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Molybdenum'),
        ),
        migrations.AlterField(
            model_name='mineralsandtraceelements',
            name='na',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Sodium'),
        ),
        migrations.AlterField(
            model_name='mineralsandtraceelements',
            name='ni',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Nickel'),
        ),
        migrations.AlterField(
            model_name='mineralsandtraceelements',
            name='p',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Phosphorus'),
        ),
        migrations.AlterField(
            model_name='mineralsandtraceelements',
            name='pb',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Lead'),
        ),
        migrations.AlterField(
            model_name='mineralsandtraceelements',
            name='se',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Selenium'),
        ),
        migrations.AlterField(
            model_name='mineralsandtraceelements',
            name='zn',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Zinc'),
        ),
        migrations.AlterField(
            model_name='oligosaccharides',
            name='ajus',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Ajugose'),
        ),
        migrations.AlterField(
            model_name='oligosaccharides',
            name='rafs',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Raffinose'),
        ),
        migrations.AlterField(
            model_name='oligosaccharides',
            name='stas',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Stachyose'),
        ),
        migrations.AlterField(
            model_name='oligosaccharides',
            name='vers',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Verbacose'),
        ),
        migrations.AlterField(
            model_name='organicacid',
            name='cisacoacid',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='cis-Aconitic Acid'),
        ),
        migrations.AlterField(
            model_name='organicacid',
            name='citac',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Citric Acid'),
        ),
        migrations.AlterField(
            model_name='organicacid',
            name='fumac',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Fumaric Acid'),
        ),
        migrations.AlterField(
            model_name='organicacid',
            name='malac',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Malic Acid'),
        ),
        migrations.AlterField(
            model_name='organicacid',
            name='oxalateins',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Water Insoluble Oxalate'),
        ),
        migrations.AlterField(
            model_name='organicacid',
            name='oxalatesol',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Water Soluble Oxalate'),
        ),
        migrations.AlterField(
            model_name='organicacid',
            name='oxalatetot',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Total Oxalate'),
        ),
        migrations.AlterField(
            model_name='organicacid',
            name='quinic',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Quinic Acid'),
        ),
        migrations.AlterField(
            model_name='organicacid',
            name='sucac',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Succinic Acid'),
        ),
        migrations.AlterField(
            model_name='organicacid',
            name='tarac',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Tartaric Acid'),
        ),
        migrations.AlterField(
            model_name='phytosterolsphytatesaponin',
            name='bsitosterol',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='beta-Sitosterol'),
        ),
        migrations.AlterField(
            model_name='phytosterolsphytatesaponin',
            name='camt',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Campesterol'),
        ),
        migrations.AlterField(
            model_name='phytosterolsphytatesaponin',
            name='phytac',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Phytate'),
        ),
        migrations.AlterField(
            model_name='phytosterolsphytatesaponin',
            name='stgstr',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Stigmasterol'),
        ),
        migrations.AlterField(
            model_name='phytosterolsphytatesaponin',
            name='totsaponin',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Total Saponin'),
        ),
        migrations.AlterField(
            model_name='polyphenols',
            name='apigen',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Apigenin'),
        ),
        migrations.AlterField(
            model_name='polyphenols',
            name='apigen_cg',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Apigenin-6-C-gluoside'),
        ),
        migrations.AlterField(
            model_name='polyphenols',
            name='apigen_on',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Apegenin-7-O-neohesperidoside'),
        ),
        migrations.AlterField(
            model_name='polyphenols',
            name='caffeic',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Caffeic Acid'),
        ),
        migrations.AlterField(
            model_name='polyphenols',
            name='catechin',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='+ Catechin'),
        ),
        migrations.AlterField(
            model_name='polyphenols',
            name='chlrac',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Chlorogenic Acid'),
        ),
        migrations.AlterField(
            model_name='polyphenols',
            name='cinnamic',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Cinnamic Acid'),
        ),
        migrations.AlterField(
            model_name='polyphenols',
            name='daidzn',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Daidzein'),
        ),
        migrations.AlterField(
            model_name='polyphenols',
            name='dhbenzacid',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='3,4-Dihydroxybenzoic Acid'),
        ),
        migrations.AlterField(
            model_name='polyphenols',
            name='ellagic',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Ellagic Acid'),
        ),
        migrations.AlterField(
            model_name='polyphenols',
            name='epicatec',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='- Epicatechin'),
        ),
        migrations.AlterField(
            model_name='polyphenols',
            name='epicategc',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='- Epigalocatechin'),
        ),
        migrations.AlterField(
            model_name='polyphenols',
            name='epigalocg',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='- Epigalocatechin-3-gallate'),
        ),
        migrations.AlterField(
            model_name='polyphenols',
            name='ferac',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Ferulic Acid'),
        ),
        migrations.AlterField(
            model_name='polyphenols',
            name='gallic',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Gallic Acid'),
        ),
        migrations.AlterField(
            model_name='polyphenols',
            name='gallocatechin_ga',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Gallocatechin gallate'),
        ),
        migrations.AlterField(
            model_name='polyphenols',
            name='gallocatecin',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Gallocatechin'),
        ),
        migrations.AlterField(
            model_name='polyphenols',
            name='gnstein',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Genistein'),
        ),
        migrations.AlterField(
            model_name='polyphenols',
            name='hespd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Hesperdin'),
        ),
        migrations.AlterField(
            model_name='polyphenols',
            name='hespt',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Hesperetin'),
        ),
        migrations.AlterField(
            model_name='polyphenols',
            name='isorhamnetin',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Isorhamnetin'),
        ),
        migrations.AlterField(
            model_name='polyphenols',
            name='kaemf',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Kaempferol'),
        ),
        migrations.AlterField(
            model_name='polyphenols',
            name='luteol',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Luteolin'),
        ),
        migrations.AlterField(
            model_name='polyphenols',
            name='myricetin',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Myricetin'),
        ),
        migrations.AlterField(
            model_name='polyphenols',
            name='naringenin',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Naringenin'),
        ),
        migrations.AlterField(
            model_name='polyphenols',
            name='o_coumaric',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='O-Coumaric Acid'),
        ),
        migrations.AlterField(
            model_name='polyphenols',
            name='p_coumaric',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='P-Coumaric Acid'),
        ),
        migrations.AlterField(
            model_name='polyphenols',
            name='protocatechuic',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Protocatechuic Acid'),
        ),
        migrations.AlterField(
            model_name='polyphenols',
            name='querce',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Quercetin'),
        ),
        migrations.AlterField(
            model_name='polyphenols',
            name='querce_bd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Quercetin 3-beta-D-glucoside'),
        ),
        migrations.AlterField(
            model_name='polyphenols',
            name='querce_bg',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Quercetin-3-beta-galactoside'),
        ),
        migrations.AlterField(
            model_name='polyphenols',
            name='querce_or',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Quercetin 3-O-rutinoside'),
        ),
        migrations.AlterField(
            model_name='polyphenols',
            name='resveratol',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Resveratrol'),
        ),
        migrations.AlterField(
            model_name='polyphenols',
            name='sinapinic',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Sinapinic Acid'),
        ),
        migrations.AlterField(
            model_name='polyphenols',
            name='syringic',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Syringic Acid'),
        ),
        migrations.AlterField(
            model_name='polyphenols',
            name='total_poly',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Total Polyphenols'),
        ),
        migrations.AlterField(
            model_name='polyphenols',
            name='vanillic',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Vanillic Acid'),
        ),
        migrations.AlterField(
            model_name='starchandsugars',
            name='frus',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Fructose'),
        ),
        migrations.AlterField(
            model_name='starchandsugars',
            name='glus',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Glucose'),
        ),
        migrations.AlterField(
            model_name='starchandsugars',
            name='mals',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Maltose'),
        ),
        migrations.AlterField(
            model_name='starchandsugars',
            name='starch',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Starch'),
        ),
        migrations.AlterField(
            model_name='starchandsugars',
            name='sucs',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Sucrose'),
        ),
        migrations.AlterField(
            model_name='starchandsugars',
            name='tacho',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Total Available Carbohydrates'),
        ),
        migrations.AlterField(
            model_name='starchandsugars',
            name='tfs',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Total Free Sugars'),
        ),
        migrations.AlterField(
            model_name='watersolublevitamins',
            name='biot',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Biotin'),
        ),
        migrations.AlterField(
            model_name='watersolublevitamins',
            name='folsum',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Folic Acid'),
        ),
        migrations.AlterField(
            model_name='watersolublevitamins',
            name='nia',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Niacin'),
        ),
        migrations.AlterField(
            model_name='watersolublevitamins',
            name='pantac',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Pantothenic Acid'),
        ),
        migrations.AlterField(
            model_name='watersolublevitamins',
            name='ribf',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Riboflavin'),
        ),
        migrations.AlterField(
            model_name='watersolublevitamins',
            name='thia',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Thiamine (Vitamin B1)'),
        ),
        migrations.AlterField(
            model_name='watersolublevitamins',
            name='vitb6a',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Vitamin B6'),
        ),
        migrations.AlterField(
            model_name='watersolublevitamins',
            name='vitc',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Vitamin C'),
        ),
    ]
