# Generated by Django 5.1.4 on 2025-08-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhaiapp', '0007_remove_polyphenols_hbenzaldehyde_aminoacid_ala_sd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietaryfibre',
            name='water_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Water Content Deviation'),
        ),
    ]
