# Generated by Django 5.2.5 on 2025-08-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhaiapp', '0008_dietaryfibre_water_sd'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatsolublevitamins',
            name='hychocal',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='HydroxyCholecalciferol (Vitamin D3)'),
        ),
        migrations.AddField(
            model_name='fatsolublevitamins',
            name='hychocal_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='HydroxyCholecalciferol (Vitamin D3) Standard Deviation'),
        ),
    ]
