# Generated by Django 5.2.5 on 2025-08-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhaiapp', '0009_fatsolublevitamins_hychocal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatsolublevitamins',
            name='tocpha',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Tocopherol (Vitamin E)'),
        ),
        migrations.AlterField(
            model_name='fatsolublevitamins',
            name='tocpha_sd',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Tocopherol Standard Deviation'),
        ),
    ]
