# Generated by Django 5.2.5 on 2025-09-06 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhaiapp', '0010_alter_fatsolublevitamins_tocpha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietaryfibre',
            name='food_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='food_dietary_fibre', to='fhaiapp.food'),
        ),
    ]
